### ISSUE TITLE
setSelectedRows([]) should clear active cells

### ISSUE THREAD

**Issue by ThomasArdal** [mleibman/SlickGrid#391]
When calling setSelectedRows on grid with an empty array, the selected rows in the grid is removed. But the previous selected cell is still marked as active, even though the row containing the cell is not longer selected.

**Comment by sswam** [comment]
The problem here is that if I click on a row, then call grid.setSelectedCells([]) in javascript console for example, then click on the same row again, it does not select or highlight the row because it was already "active".  Those concepts really are connected, it won't select a row that is already active.

**Comment by 6pac** [comment]
as suggested above, call

```
grid.setSelectedRows([]);
grid.resetActiveCell();
```

both selection and active cell will be reset.

**Comment by simpysodhi1981** [comment]
grid.resetActiveCell(); throws JS error: currentEditor is null with latest slickgrid

**Comment by 6pac** [comment]
this is probably fixed, along with many other issues, in [my new master repo](https://github.com/6pac/SlickGrid), which you should be using anyway. if it's not fixed, raise an issue over there.

**Comment by simpysodhi1981** [comment]
I tried your new master repo, but still this issue exists. I posted there too.

thanks
